---
# Generate kubeconfig.

- name: Generate kubeconfig for master components
  shell: kubeadm alpha phase kubeconfig client-certs --client-name {{ item[0].client }} --server https://{{ hostvars[item[1]]['ansible_host'] }}:6443 > {{ kube_config_dir }}/{{ item[0].name }}-{{ item[1] }}.kubeconfig
  with_nested:
    -
      - name: scheduler
        client: system:kube-scheduler
      - name: controller-manager
        client: system:kube-controller-manager
    - "{{ groups['masters'] }}"

- name: Generate kubeconfig for master components
  shell: kubeadm alpha phase kubeconfig client-certs --client-name {{ item[0].client_prefix }}{{ hostvars[item[1]]['ansible_hostname'] }} --organization {{ item[0].org }} --server https://{{ hostvars[item[1]]['ansible_host'] }}:6443 > {{ kube_config_dir }}/{{ item[0].name }}-{{ item[1] }}.kubeconfig
  with_nested:
    -
      - name: kubelet
        client_prefix: "system:node:"
        org: system:nodes
    - "{{ groups['masters'] }}"

- name: Generate kubeconfig for node components
  shell: kubeadm alpha phase kubeconfig client-certs --client-name {{ item[0].client_prefix }}{{ hostvars[item[1]]['ansible_hostname'] }} --organization {{ item[0].org }} --server https://{{ kube_apiserver_endpoint_ip }} > {{ kube_config_dir }}/{{ item[0].name }}-{{ item[1] }}.kubeconfig
  with_nested:
    -
      - name: kubelet
        client_prefix: "system:node:"
        org: system:nodes
    - "{{ groups['nodes'] }}"
  when: groups['nodes'] is defined


- name: Generate kubeconfig for admin
  shell: kubeadm alpha phase kubeconfig client-certs --client-name {{ item.client }} --organization {{ item.org }} --server https://{{ kube_apiserver_endpoint_ip }} > {{ kube_config_dir }}/{{ item.name }}.kubeconfig
  with_items:
    - name: admin
      client: kubernetes-admin
      org: system:masters
