---
# Place kubeconfig.

- name: Make sure {{ kube_config_dir }} directory exists
  file: path={{ kube_config_dir }} state=directory

- name: Place kubeconfig on masters
  copy:
    src: "{{ kube_config_dir }}/{{ item }}-{{ inventory_hostname }}.kubeconfig"
    dest: "{{ kube_config_dir }}/{{ item }}.kubeconfig"
  with_items:
    - kubelet
    - scheduler
    - controller-manager
  when: inventory_hostname in groups['masters']

- name: Place kubeconfig on nodes
  copy:
    src: "{{ kube_config_dir }}/{{ item }}-{{ inventory_hostname }}.kubeconfig"
    dest: "{{ kube_config_dir }}/{{ item }}.kubeconfig"
  with_items:
    - kubelet
  when: groups['nodes'] is defined and inventory_hostname in groups['nodes']

- name: Place admin kubeconfig on masters
  copy:
    src: "{{ kube_config_dir }}/{{ item }}.kubeconfig"
    dest: "{{ kube_config_dir }}/{{ item }}.kubeconfig"
  with_items:
    - admin
  when: inventory_hostname in groups['masters']
