---
# Start services.

- name: Enable and start services
  service: name="{{ item }}" enabled=yes state=restarted
  with_items:
    - docker
    - kubelet

- name: Wait for the apiserver to be running
  uri: url=https://localhost:6443/healthz validate_certs=no
  register: result
  until: result.status is defined and result.status == 200
  retries: 45
  delay: 20
  when: inventory_hostname in groups['masters']

- name: Wait for the load balancer to be running
  uri: url=https://{{ kube_apiserver_endpoint_ip }}/healthz validate_certs=no
  register: result
  until: result.status is defined and result.status == 200
  retries: 45
  delay: 20
  when: inventory_hostname == groups['masters'][0]
